name: base
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
- bcftools<=1.22
- bedtools<=2.31.1
- bzip2<=1.0.8
- mosdepth<=0.3.10
- python<=3.13
- samtools<=1.22
- pip
- pip:
  - gauchian<=1.0.2
  - multiqc<=1.30
  - pandas<=2.3.0